
name: Release PowerShell Module

on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release PowerShell Module
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Publish PowerShell Module
        id: publish
        shell: pwsh
        run: |
          pwsh ./build/Publish-MyModule.ps1 -Path "./EntraIdDSC/" -ApiKey "${{ secrets.PSGALLERY_API_KEY }}"

      - name: Read Manifest File for the current version
        id: read_manifest
        shell: pwsh
        run: |
          $manifest = Get-ChildItem -Path './EntraIdDSC/' -Filter '*.psd1' | Select-Object -First 1
          if ($null -eq $manifest) {
            Write-Error 'No manifest file (*.psd1) found in ./EntraIdDSC/'
            exit 1
          }
          $manifestObject = Import-PowerShellDataFile -Path $manifest.FullName
          $version = $manifestObject.ModuleVersion
          Add-Content -Path $env:GITHUB_ENV -Value "MODULE_VERSION=$version"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.MODULE_VERSION }}
          name: Version ${{ env.MODULE_VERSION }}
          draft: false
          prerelease: false
